# Site settings
title: "Awesome Reviewers"
description: "Ready-to-use system prompts extracted from thousands of code review comments in leading open source repositories"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://awesomereviewers.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  reviewers:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Include raw reviewer JSON files
include:
  - _reviewers/*.json

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "reviewers"
    values:
      layout: "reviewer"
