name: Update search files
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyyaml
      - name: Generate llms.txt and robots.txt
        run: python scripts/update_search_files.py
      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain robots.txt llms.txt)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add robots.txt llms.txt
            git commit -m "Update robots.txt and llms.txt"
            git push
          fi

